# Generated by Django 6.0.6 on 2026-07-06 00:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DebateSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('panel', 'Panel'), ('mediator', 'Mediator')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('ready', 'Ready'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='ready', max_length=20)),
                ('calibration_context', models.JSONField(default=dict)),
                ('panel_snapshot', models.JSONField(default=list)),
                ('mediator_snapshot', models.JSONField(default=dict)),
                ('current_round', models.PositiveSmallIntegerField(default=0)),
                ('current_stage', models.CharField(default='ready', max_length=50)),
                ('openai_conversation_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debate_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DebateMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField()),
                ('speaker_id', models.CharField(max_length=100)),
                ('speaker_type', models.CharField(choices=[('user', 'User'), ('panel', 'Panel Member'), ('mediator', 'Mediator'), ('system', 'System')], max_length=20)),
                ('message_type', models.CharField(choices=[('position', 'Position'), ('challenge', 'Challenge'), ('response', 'Response'), ('intervention', 'Intervention'), ('synthesis', 'Synthesis'), ('verdict', 'Verdict')], max_length=30)),
                ('content', models.TextField()),
                ('emotion', models.CharField(blank=True, max_length=50)),
                ('animation', models.CharField(blank=True, max_length=50)),
                ('round_number', models.PositiveSmallIntegerField(default=1)),
                ('stage', models.CharField(max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chamber.debatesession')),
            ],
            options={
                'ordering': ['sequence'],
                'constraints': [models.UniqueConstraint(fields=('session', 'sequence'), name='unique_session_message_sequence')],
            },
        ),
    ]
