# Generated by Django 6.0.6 on 2026-07-06 12:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamber', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebateReaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('character_id', models.CharField(max_length=100)),
                ('reaction', models.CharField(choices=[('agree', 'Agree'), ('disagree', 'Disagree')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['character_id'],
            },
        ),
        migrations.CreateModel(
            name='DebateRound',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section_id', models.CharField(default='main', max_length=100)),
                ('number', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('active', 'Active'), ('complete', 'Complete')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['section_id', 'number'],
            },
        ),
        migrations.CreateModel(
            name='FocusedDiscussion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section_id', models.CharField(default='main', max_length=100)),
                ('character_id', models.CharField(max_length=100)),
                ('source_type', models.CharField(choices=[('risk', 'Risk'), ('action', 'Action'), ('statement', 'Statement'), ('disagreement', 'Disagreement'), ('question', 'Question'), ('other', 'Other')], max_length=30)),
                ('source_id', models.CharField(blank=True, max_length=150)),
                ('topic', models.TextField()),
                ('title', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='active', max_length=20)),
                ('conclusion', models.TextField(blank=True)),
                ('mediator_state', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='FocusedDiscussionMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField()),
                ('speaker_id', models.CharField(max_length=100)),
                ('speaker_type', models.CharField(choices=[('user', 'User'), ('character', 'Character'), ('mediator', 'Mediator'), ('system', 'System')], max_length=20)),
                ('message_type', models.CharField(choices=[('message', 'Message'), ('response', 'Response'), ('synthesis', 'Synthesis')], max_length=30)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.AlterField(
            model_name='debatemessage',
            name='message_type',
            field=models.CharField(choices=[('position', 'Position'), ('challenge', 'Challenge'), ('response', 'Response'), ('intervention', 'Intervention'), ('council_reply', 'Council Reply'), ('opposing_view', 'Opposing View'), ('synthesis', 'Synthesis'), ('verdict', 'Verdict')], max_length=30),
        ),
        migrations.AlterField(
            model_name='debatemessage',
            name='stage',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='debatesession',
            name='current_stage',
            field=models.CharField(default='ready', max_length=100),
        ),
        migrations.AddIndex(
            model_name='debatemessage',
            index=models.Index(fields=['session', 'round_number'], name='debate_message_round'),
        ),
        migrations.AddIndex(
            model_name='debatemessage',
            index=models.Index(fields=['session', 'stage'], name='debate_message_stage'),
        ),
        migrations.AddField(
            model_name='debateround',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='chamber.debatesession'),
        ),
        migrations.AddField(
            model_name='debatereaction',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='chamber.debateround'),
        ),
        migrations.AddField(
            model_name='focuseddiscussion',
            name='round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='focused_discussions', to='chamber.debateround'),
        ),
        migrations.AddField(
            model_name='focuseddiscussion',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='focused_discussions', to='chamber.debatesession'),
        ),
        migrations.AddField(
            model_name='focuseddiscussionmessage',
            name='discussion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chamber.focuseddiscussion'),
        ),
        migrations.AddIndex(
            model_name='debateround',
            index=models.Index(fields=['session', 'section_id', 'number'], name='debate_round_lookup'),
        ),
        migrations.AddConstraint(
            model_name='debateround',
            constraint=models.UniqueConstraint(fields=('session', 'section_id', 'number'), name='unique_debate_round_per_section'),
        ),
        migrations.AddConstraint(
            model_name='debatereaction',
            constraint=models.UniqueConstraint(fields=('round', 'character_id'), name='unique_character_reaction_per_round'),
        ),
        migrations.AddIndex(
            model_name='focuseddiscussion',
            index=models.Index(fields=['session', 'section_id', 'character_id'], name='focused_discussion_lookup'),
        ),
        migrations.AddConstraint(
            model_name='focuseddiscussionmessage',
            constraint=models.UniqueConstraint(fields=('discussion', 'sequence'), name='unique_focused_discussion_message_sequence'),
        ),
    ]
