# Generated by Django 6.0.6 on 2026-07-07 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamber', '0002_debatereaction_debateround_focuseddiscussion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='debatesession',
            name='pinned',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
