# Generated by Django 6.0.6 on 2026-07-08 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamber', '0003_debatesession_pinned'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebateReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executive_summary', models.TextField(blank=True)),
                ('final_verdict', models.TextField(blank=True)),
                ('mediator_final_summary', models.TextField(blank=True)),
                ('final_confidence', models.IntegerField(blank=True, null=True)),
                ('final_risks', models.JSONField(blank=True, default=list)),
                ('final_actions', models.JSONField(blank=True, default=list)),
                ('unresolved_points', models.JSONField(blank=True, default=list)),
                ('important_notes', models.JSONField(blank=True, default=list)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='chamber.debatesession')),
            ],
        ),
        migrations.CreateModel(
            name='DebateRoundReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_id', models.CharField(default='main', max_length=100)),
                ('round_number', models.PositiveSmallIntegerField()),
                ('summary', models.TextField(blank=True)),
                ('mediator_summary', models.TextField(blank=True)),
                ('key_conflict', models.TextField(blank=True)),
                ('resolution', models.TextField(blank=True)),
                ('confidence_before', models.IntegerField(blank=True, null=True)),
                ('confidence_after', models.IntegerField(blank=True, null=True)),
                ('confidence_change', models.IntegerField(blank=True, null=True)),
                ('confidence_change_reason', models.TextField(blank=True)),
                ('important_notes', models.JSONField(blank=True, default=list)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_reports', to='chamber.debatereport')),
                ('round', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chamber.debateround')),
            ],
            options={
                'unique_together': {('report', 'section_id', 'round_number')},
            },
        ),
        migrations.CreateModel(
            name='DebateRoundUserResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_id', models.CharField(blank=True, max_length=100)),
                ('user_message', models.TextField()),
                ('response_type', models.CharField(blank=True, max_length=100)),
                ('effect', models.TextField(blank=True)),
                ('source_message_id', models.UUIDField(blank=True, null=True)),
                ('round_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_responses', to='chamber.debateroundreport')),
            ],
        ),
        migrations.CreateModel(
            name='DebateTurningPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('importance', models.CharField(default='medium', max_length=50)),
                ('confidence_before', models.IntegerField(blank=True, null=True)),
                ('confidence_after', models.IntegerField(blank=True, null=True)),
                ('source_message_ids', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turning_points', to='chamber.debatereport')),
                ('round_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chamber.debateroundreport')),
            ],
        ),
        migrations.CreateModel(
            name='DebateRoundMemberReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_id', models.CharField(max_length=100)),
                ('character_name', models.CharField(blank=True, max_length=150)),
                ('role', models.CharField(blank=True, max_length=150)),
                ('stance', models.TextField(blank=True)),
                ('thoughts', models.TextField(blank=True)),
                ('reasoning', models.TextField(blank=True)),
                ('confidence_before', models.IntegerField(blank=True, null=True)),
                ('confidence_after', models.IntegerField(blank=True, null=True)),
                ('confidence_change_reason', models.TextField(blank=True)),
                ('risks', models.JSONField(blank=True, default=list)),
                ('actions', models.JSONField(blank=True, default=list)),
                ('agreements', models.JSONField(blank=True, default=list)),
                ('disagreements', models.JSONField(blank=True, default=list)),
                ('changed_position', models.BooleanField(default=False)),
                ('round_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_reports', to='chamber.debateroundreport')),
            ],
            options={
                'ordering': ['character_name'],
                'constraints': [models.UniqueConstraint(fields=('round_report', 'character_id'), name='unique_character_report_per_round_report')],
            },
        ),
    ]
